sonar.projectKey=server-product
sonar.sources=src/main
sonar.tests=src/test
sonar.java.binaries=target
sonar.junit.reportPaths=target/surefire-reports
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml