INSERT INTO public.amenities (id, icon, "name") VALUES(1, 'https://statics.travala.com/facilities-icon/check_travo.svg', 'Dịch vụ trông giữ vật nuôi');
INSERT INTO public.amenities (id, icon, "name") VALUES(2, 'https://statics.travala.com/facilities-icon/Bar_travo.svg', 'Bar/lounge');
INSERT INTO public.amenities (id, icon, "name") VALUES(3, 'https://statics.travala.com/facilities-icon/Laundry_travo.svg', 'Dịch vụ giặt khô/giặt ủi');
INSERT INTO public.amenities (id, icon, "name") VALUES(4, 'https://statics.travala.com/facilities-icon/Fitness-Center_travo.svg', 'Khu thể thao');
INSERT INTO public.amenities (id, icon, "name") VALUES(5, 'https://statics.travala.com/facilities-icon/Luggage-storage_travo.svg', 'Trông giữ/bảo quản hành lý');
INSERT INTO public.amenities (id, icon, "name") VALUES(6, 'https://statics.travala.com/facilities-icon/Spa_travo.svg', 'Bồn tắm spa (phụ phí)');
INSERT INTO public.amenities (id, icon, "name") VALUES(7, 'https://statics.travala.com/facilities-icon/check_travo.svg', 'Dịch vụ cắt tỉa lông cho vật nuôi');
INSERT INTO public.amenities (id, icon, "name") VALUES(8, 'https://statics.travala.com/facilities-icon/Swimming_travo.svg', 'Hồ bơi');
INSERT INTO public.amenities (id, icon, "name") VALUES(9, 'https://statics.travala.com/facilities-icon/Tour-Desk_travo.svg', 'Dịch vụ hỗ trợ tour/vé du lịch');
INSERT INTO public.amenities (id, icon, "name") VALUES(10, 'https://statics.travala.com/facilities-icon/smoking_travo.svg', 'Khách sạn không khói thuốc');
INSERT INTO public.amenities (id, icon, "name") VALUES(11, 'https://statics.travala.com/facilities-icon/Spa_travo.svg', 'Bồn tắm spa');
INSERT INTO public.amenities (id, icon, "name") VALUES(12, 'https://statics.travala.com/facilities-icon/wifi.svg', 'Wifi miễn phí');
