--
-- PostgreSQL database dump
--

-- Dumped from database version 14.3
-- Dumped by pg_dump version 14.3

-- Started on 2025-06-15 21:48:11

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

DROP DATABASE travel_support;
--
-- TOC entry 3464 (class 1262 OID 16527)
-- Name: travel_support; Type: DATABASE; Schema: -; Owner: postgres
--

CREATE DATABASE travel_support WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE = 'Vietnamese_Vietnam.1252';


ALTER DATABASE travel_support OWNER TO postgres;

\connect travel_support

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 3465 (class 0 OID 0)
-- Dependencies: 3464
-- Name: DATABASE travel_support; Type: COMMENT; Schema: -; Owner: postgres
--

COMMENT ON DATABASE travel_support IS 'Application travel support';


--
-- TOC entry 3 (class 2615 OID 2200)
-- Name: public; Type: SCHEMA; Schema: -; Owner: postgres
--

CREATE SCHEMA public;


ALTER SCHEMA public OWNER TO postgres;

--
-- TOC entry 3466 (class 0 OID 0)
-- Dependencies: 3
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: postgres
--

COMMENT ON SCHEMA public IS 'standard public schema';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 209 (class 1259 OID 16528)
-- Name: account; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.account (
    id character varying(255) NOT NULL,
    created_at timestamp without time zone,
    updated_at timestamp without time zone,
    version integer NOT NULL,
    dob character varying(255),
    email character varying(255),
    enabled boolean,
    gender boolean,
    image_link character varying(255),
    name character varying(255),
    password character varying(255),
    phone character varying(255),
    reset_password_token character varying(255),
    role_id bigint
);


ALTER TABLE public.account OWNER TO postgres;

--
-- TOC entry 210 (class 1259 OID 16535)
-- Name: activities; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.activities (
    id character varying(255) NOT NULL,
    created_at timestamp without time zone,
    updated_at timestamp without time zone,
    version integer NOT NULL,
    type character varying(255),
    address character varying(255),
    adult_ticket_price double precision,
    approve_status character varying(255),
    child_ticket_price double precision,
    code character varying(255),
    description text,
    duration integer,
    slug character varying(1000),
    star integer,
    title character varying(1000),
    user_id character varying(255)
);


ALTER TABLE public.activities OWNER TO postgres;

--
-- TOC entry 212 (class 1259 OID 16543)
-- Name: activities_game; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.activities_game (
    id integer NOT NULL,
    activities_code character varying(255),
    description text,
    image character varying(255),
    name character varying(255)
);


ALTER TABLE public.activities_game OWNER TO postgres;

--
-- TOC entry 211 (class 1259 OID 16542)
-- Name: activities_game_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.activities_game ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.activities_game_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 213 (class 1259 OID 16550)
-- Name: activities_image; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.activities_image (
    id bigint NOT NULL,
    created_at timestamp without time zone,
    updated_at timestamp without time zone,
    version integer NOT NULL,
    activities_code character varying(255),
    caption text,
    url character varying(255)
);


ALTER TABLE public.activities_image OWNER TO postgres;

--
-- TOC entry 214 (class 1259 OID 16557)
-- Name: activities_receipt; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.activities_receipt (
    id character varying(255) NOT NULL,
    created_at timestamp without time zone,
    updated_at timestamp without time zone,
    version integer NOT NULL,
    activities_info jsonb,
    booking_id character varying(255),
    number_ticket_adult integer,
    number_ticket_child integer,
    partner_id character varying(255),
    phone_partner character varying(255),
    price double precision,
    status character varying(255),
    travel_date integer,
    user_id character varying(255),
    contact_id character varying(255)
);


ALTER TABLE public.activities_receipt OWNER TO postgres;

--
-- TOC entry 216 (class 1259 OID 16565)
-- Name: amenities; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.amenities (
    id integer NOT NULL,
    icon character varying(255),
    name character varying(255)
);


ALTER TABLE public.amenities OWNER TO postgres;

--
-- TOC entry 215 (class 1259 OID 16564)
-- Name: amenities_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.amenities ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.amenities_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 217 (class 1259 OID 16572)
-- Name: booking_contact; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.booking_contact (
    id character varying(255) NOT NULL,
    created_at timestamp without time zone,
    updated_at timestamp without time zone,
    version integer NOT NULL,
    customer_id character varying(255),
    email character varying(255),
    first_name character varying(255),
    last_name character varying(255),
    phone character varying(255)
);


ALTER TABLE public.booking_contact OWNER TO postgres;

--
-- TOC entry 218 (class 1259 OID 16579)
-- Name: favorite; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.favorite (
    id character varying(255) NOT NULL,
    created_at timestamp without time zone,
    updated_at timestamp without time zone,
    version integer NOT NULL,
    image_url character varying(255),
    slug character varying(255),
    title character varying(255),
    type character varying(255) NOT NULL,
    user_id character varying(255)
);


ALTER TABLE public.favorite OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 16586)
-- Name: favorite_hotel; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.favorite_hotel (
    id character varying(255) NOT NULL,
    created_at timestamp without time zone,
    updated_at timestamp without time zone,
    version integer NOT NULL,
    hotel_data jsonb,
    product_code character varying(255),
    slug character varying(255),
    user_id character varying(255)
);


ALTER TABLE public.favorite_hotel OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 16594)
-- Name: feature; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.feature (
    id integer NOT NULL,
    name text
);


ALTER TABLE public.feature OWNER TO postgres;

--
-- TOC entry 220 (class 1259 OID 16593)
-- Name: feature_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.feature ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.feature_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 233 (class 1259 OID 16677)
-- Name: hibernate_sequence; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.hibernate_sequence
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.hibernate_sequence OWNER TO postgres;

--
-- TOC entry 222 (class 1259 OID 16601)
-- Name: hotel; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.hotel (
    id character varying(255) NOT NULL,
    created_at timestamp without time zone,
    updated_at timestamp without time zone,
    version integer NOT NULL,
    address character varying(255),
    amenities integer[],
    approve_status character varying(255),
    code character varying(255),
    description text,
    hotel_type character varying(255),
    min_price double precision,
    rank integer,
    slug character varying(1000),
    star double precision,
    title character varying(1000),
    user_id character varying(255)
);


ALTER TABLE public.hotel OWNER TO postgres;

--
-- TOC entry 223 (class 1259 OID 16608)
-- Name: hotel_bookable_item; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.hotel_bookable_item (
    id bigint NOT NULL,
    created_at timestamp without time zone,
    updated_at timestamp without time zone,
    version integer NOT NULL,
    amenities integer[],
    available boolean,
    currency character varying(255),
    hotel_code character varying(255),
    hotel_option_code character varying(255),
    image character varying(255),
    price double precision,
    room_type character varying(255)
);


ALTER TABLE public.hotel_bookable_item OWNER TO postgres;

--
-- TOC entry 224 (class 1259 OID 16615)
-- Name: hotel_image; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.hotel_image (
    id bigint NOT NULL,
    created_at timestamp without time zone,
    updated_at timestamp without time zone,
    version integer NOT NULL,
    caption text,
    hotel_code character varying(255),
    image_type character varying(255),
    url character varying(255)
);


ALTER TABLE public.hotel_image OWNER TO postgres;

--
-- TOC entry 225 (class 1259 OID 16622)
-- Name: hotel_receipt; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.hotel_receipt (
    id character varying(255) NOT NULL,
    created_at timestamp without time zone,
    updated_at timestamp without time zone,
    version integer NOT NULL,
    booking_id character varying(255),
    from_date integer,
    to_date integer,
    hotel_info jsonb,
    package_info jsonb,
    partner_id character varying(255),
    phone_partner character varying(255),
    price double precision,
    status character varying(255),
    total_nights integer,
    user_id character varying(255),
    contact_id character varying(255)
);


ALTER TABLE public.hotel_receipt OWNER TO postgres;

--
-- TOC entry 226 (class 1259 OID 16629)
-- Name: post; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.post (
    id character varying(255) NOT NULL,
    created_at timestamp without time zone,
    updated_at timestamp without time zone,
    version integer NOT NULL,
    content text,
    image character varying(255),
    title character varying(255)
);


ALTER TABLE public.post OWNER TO postgres;

--
-- TOC entry 227 (class 1259 OID 16636)
-- Name: restaurant; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.restaurant (
    id character varying(255) NOT NULL,
    created_at timestamp without time zone,
    updated_at timestamp without time zone,
    version integer NOT NULL,
    address character varying(255),
    approve_status character varying(255),
    code character varying(255),
    description text,
    feature integer[],
    restaurant_type character varying(255),
    slug character varying(1000),
    title character varying(1000),
    user_id character varying(255)
);


ALTER TABLE public.restaurant OWNER TO postgres;

--
-- TOC entry 228 (class 1259 OID 16643)
-- Name: restaurant_image; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.restaurant_image (
    id bigint NOT NULL,
    created_at timestamp without time zone,
    updated_at timestamp without time zone,
    version integer NOT NULL,
    caption text,
    image_type character varying(255),
    restaurant_code character varying(255),
    url character varying(255)
);


ALTER TABLE public.restaurant_image OWNER TO postgres;

--
-- TOC entry 229 (class 1259 OID 16650)
-- Name: restaurant_menu; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.restaurant_menu (
    id bigint NOT NULL,
    available boolean,
    currency character varying(255),
    description character varying(255),
    image character varying(255),
    name character varying(255),
    price double precision,
    restaurant_code character varying(255)
);


ALTER TABLE public.restaurant_menu OWNER TO postgres;

--
-- TOC entry 230 (class 1259 OID 16657)
-- Name: restaurant_receipt; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.restaurant_receipt (
    id character varying(255) NOT NULL,
    created_at timestamp without time zone,
    updated_at timestamp without time zone,
    version integer NOT NULL,
    booking_id character varying(255),
    checkin_day integer,
    checkin_time character varying(255),
    number_adult integer,
    number_child integer,
    partner_id character varying(255),
    phone_partner character varying(255),
    restaurant_info jsonb,
    status character varying(255),
    user_id character varying(255),
    contact_id character varying(255)
);


ALTER TABLE public.restaurant_receipt OWNER TO postgres;

--
-- TOC entry 232 (class 1259 OID 16665)
-- Name: role; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.role (
    id bigint NOT NULL,
    name character varying(255)
);


ALTER TABLE public.role OWNER TO postgres;

--
-- TOC entry 231 (class 1259 OID 16664)
-- Name: role_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.role ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.role_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 3434 (class 0 OID 16528)
-- Dependencies: 209
-- Data for Name: account; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.account VALUES ('9f75eb3a-e476-48a8-93e1-8fd97c4dd71c', '2025-06-15 17:15:57.333787', '2025-06-15 17:15:57.333787', 0, '20000101', 'tuantain2003@gmail.com', true, true, NULL, 'Nguyễn Tuấn Tài', '$2a$12$26y5/NJ/LRB3zDtuXC2TB.4zmmGhU9uHV1MBjifObaYkFFcj/zq/a', '0988765234', NULL, 5);
INSERT INTO public.account VALUES ('acc001', '2025-06-15 17:43:31.678594', '2025-06-15 17:43:31.678594', 1, '1999-05-20', 'tuantai1999@gmail.com', true, true, 'https://example.com/image.jpg', 'Nguyễn Tuấn Tài', '$2a$12$FUVbQggj.Mv1Jw8ZiZv6Ue0zXD9qs6tbZQHV9uINNJPIBbgZ84wWa', '0988765382', NULL, 1);


--
-- TOC entry 3435 (class 0 OID 16535)
-- Dependencies: 210
-- Data for Name: activities; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 3437 (class 0 OID 16543)
-- Dependencies: 212
-- Data for Name: activities_game; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 3438 (class 0 OID 16550)
-- Dependencies: 213
-- Data for Name: activities_image; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 3439 (class 0 OID 16557)
-- Dependencies: 214
-- Data for Name: activities_receipt; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 3441 (class 0 OID 16565)
-- Dependencies: 216
-- Data for Name: amenities; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 3442 (class 0 OID 16572)
-- Dependencies: 217
-- Data for Name: booking_contact; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 3443 (class 0 OID 16579)
-- Dependencies: 218
-- Data for Name: favorite; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 3444 (class 0 OID 16586)
-- Dependencies: 219
-- Data for Name: favorite_hotel; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 3446 (class 0 OID 16594)
-- Dependencies: 221
-- Data for Name: feature; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 3447 (class 0 OID 16601)
-- Dependencies: 222
-- Data for Name: hotel; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 3448 (class 0 OID 16608)
-- Dependencies: 223
-- Data for Name: hotel_bookable_item; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 3449 (class 0 OID 16615)
-- Dependencies: 224
-- Data for Name: hotel_image; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 3450 (class 0 OID 16622)
-- Dependencies: 225
-- Data for Name: hotel_receipt; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 3451 (class 0 OID 16629)
-- Dependencies: 226
-- Data for Name: post; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 3452 (class 0 OID 16636)
-- Dependencies: 227
-- Data for Name: restaurant; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 3453 (class 0 OID 16643)
-- Dependencies: 228
-- Data for Name: restaurant_image; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 3454 (class 0 OID 16650)
-- Dependencies: 229
-- Data for Name: restaurant_menu; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 3455 (class 0 OID 16657)
-- Dependencies: 230
-- Data for Name: restaurant_receipt; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 3457 (class 0 OID 16665)
-- Dependencies: 232
-- Data for Name: role; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.role VALUES (5, 'User');
INSERT INTO public.role VALUES (1, 'Admin');


--
-- TOC entry 3467 (class 0 OID 0)
-- Dependencies: 211
-- Name: activities_game_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.activities_game_id_seq', 1, false);


--
-- TOC entry 3468 (class 0 OID 0)
-- Dependencies: 215
-- Name: amenities_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.amenities_id_seq', 1, false);


--
-- TOC entry 3469 (class 0 OID 0)
-- Dependencies: 220
-- Name: feature_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.feature_id_seq', 1, false);


--
-- TOC entry 3470 (class 0 OID 0)
-- Dependencies: 233
-- Name: hibernate_sequence; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.hibernate_sequence', 1, false);


--
-- TOC entry 3471 (class 0 OID 0)
-- Dependencies: 231
-- Name: role_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.role_id_seq', 1, false);


--
-- TOC entry 3245 (class 2606 OID 16534)
-- Name: account account_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.account
    ADD CONSTRAINT account_pkey PRIMARY KEY (id);


--
-- TOC entry 3251 (class 2606 OID 16549)
-- Name: activities_game activities_game_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.activities_game
    ADD CONSTRAINT activities_game_pkey PRIMARY KEY (id);


--
-- TOC entry 3254 (class 2606 OID 16556)
-- Name: activities_image activities_image_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.activities_image
    ADD CONSTRAINT activities_image_pkey PRIMARY KEY (id);


--
-- TOC entry 3249 (class 2606 OID 16541)
-- Name: activities activities_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.activities
    ADD CONSTRAINT activities_pkey PRIMARY KEY (id);


--
-- TOC entry 3256 (class 2606 OID 16563)
-- Name: activities_receipt activities_receipt_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.activities_receipt
    ADD CONSTRAINT activities_receipt_pkey PRIMARY KEY (id);


--
-- TOC entry 3258 (class 2606 OID 16571)
-- Name: amenities amenities_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.amenities
    ADD CONSTRAINT amenities_pkey PRIMARY KEY (id);


--
-- TOC entry 3260 (class 2606 OID 16578)
-- Name: booking_contact booking_contact_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.booking_contact
    ADD CONSTRAINT booking_contact_pkey PRIMARY KEY (id);


--
-- TOC entry 3264 (class 2606 OID 16592)
-- Name: favorite_hotel favorite_hotel_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.favorite_hotel
    ADD CONSTRAINT favorite_hotel_pkey PRIMARY KEY (id);


--
-- TOC entry 3262 (class 2606 OID 16585)
-- Name: favorite favorite_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.favorite
    ADD CONSTRAINT favorite_pkey PRIMARY KEY (id);


--
-- TOC entry 3266 (class 2606 OID 16600)
-- Name: feature feature_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.feature
    ADD CONSTRAINT feature_pkey PRIMARY KEY (id);


--
-- TOC entry 3270 (class 2606 OID 16614)
-- Name: hotel_bookable_item hotel_bookable_item_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.hotel_bookable_item
    ADD CONSTRAINT hotel_bookable_item_pkey PRIMARY KEY (id);


--
-- TOC entry 3274 (class 2606 OID 16621)
-- Name: hotel_image hotel_image_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.hotel_image
    ADD CONSTRAINT hotel_image_pkey PRIMARY KEY (id);


--
-- TOC entry 3268 (class 2606 OID 16607)
-- Name: hotel hotel_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.hotel
    ADD CONSTRAINT hotel_pkey PRIMARY KEY (id);


--
-- TOC entry 3276 (class 2606 OID 16628)
-- Name: hotel_receipt hotel_receipt_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.hotel_receipt
    ADD CONSTRAINT hotel_receipt_pkey PRIMARY KEY (id);


--
-- TOC entry 3278 (class 2606 OID 16635)
-- Name: post post_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.post
    ADD CONSTRAINT post_pkey PRIMARY KEY (id);


--
-- TOC entry 3283 (class 2606 OID 16649)
-- Name: restaurant_image restaurant_image_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.restaurant_image
    ADD CONSTRAINT restaurant_image_pkey PRIMARY KEY (id);


--
-- TOC entry 3286 (class 2606 OID 16656)
-- Name: restaurant_menu restaurant_menu_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.restaurant_menu
    ADD CONSTRAINT restaurant_menu_pkey PRIMARY KEY (id);


--
-- TOC entry 3280 (class 2606 OID 16642)
-- Name: restaurant restaurant_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.restaurant
    ADD CONSTRAINT restaurant_pkey PRIMARY KEY (id);


--
-- TOC entry 3288 (class 2606 OID 16663)
-- Name: restaurant_receipt restaurant_receipt_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.restaurant_receipt
    ADD CONSTRAINT restaurant_receipt_pkey PRIMARY KEY (id);


--
-- TOC entry 3290 (class 2606 OID 16669)
-- Name: role role_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.role
    ADD CONSTRAINT role_pkey PRIMARY KEY (id);


--
-- TOC entry 3247 (class 2606 OID 16671)
-- Name: account uk_q0uja26qgu1atulenwup9rxyr; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.account
    ADD CONSTRAINT uk_q0uja26qgu1atulenwup9rxyr UNIQUE (email);


--
-- TOC entry 3252 (class 1259 OID 16672)
-- Name: activities_image_hotel_code_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX activities_image_hotel_code_idx ON public.activities_image USING btree (activities_code);


--
-- TOC entry 3272 (class 1259 OID 16674)
-- Name: hotel_image_hotel_code_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX hotel_image_hotel_code_idx ON public.hotel_image USING btree (hotel_code);


--
-- TOC entry 3271 (class 1259 OID 16673)
-- Name: p_b_i_hotel_code_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX p_b_i_hotel_code_idx ON public.hotel_bookable_item USING btree (hotel_code);


--
-- TOC entry 3284 (class 1259 OID 16676)
-- Name: r_m_restaurant_code_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX r_m_restaurant_code_idx ON public.restaurant_menu USING btree (restaurant_code);


--
-- TOC entry 3281 (class 1259 OID 16675)
-- Name: restaurant_image_code_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX restaurant_image_code_idx ON public.restaurant_image USING btree (restaurant_code);


--
-- TOC entry 3294 (class 2606 OID 16693)
-- Name: restaurant_receipt fk8tq5laypn8fkxcxgja1vqdxoh; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.restaurant_receipt
    ADD CONSTRAINT fk8tq5laypn8fkxcxgja1vqdxoh FOREIGN KEY (contact_id) REFERENCES public.booking_contact(id);


--
-- TOC entry 3291 (class 2606 OID 16678)
-- Name: account fkd4vb66o896tay3yy52oqxr9w0; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.account
    ADD CONSTRAINT fkd4vb66o896tay3yy52oqxr9w0 FOREIGN KEY (role_id) REFERENCES public.role(id);


--
-- TOC entry 3292 (class 2606 OID 16683)
-- Name: activities_receipt fkl86kxmlkveexitipcnypa8jvs; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.activities_receipt
    ADD CONSTRAINT fkl86kxmlkveexitipcnypa8jvs FOREIGN KEY (contact_id) REFERENCES public.booking_contact(id);


--
-- TOC entry 3293 (class 2606 OID 16688)
-- Name: hotel_receipt fksxv8ohy9v8cjpp3wsas99bnw9; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.hotel_receipt
    ADD CONSTRAINT fksxv8ohy9v8cjpp3wsas99bnw9 FOREIGN KEY (contact_id) REFERENCES public.booking_contact(id);


-- Completed on 2025-06-15 21:48:12

--
-- PostgreSQL database dump complete
--

